Sprint 2
microservices-course-itmo/simple-parser-service pull request #14
Opened 2020-10-06 16:45 UTC by DeLonghi

2020-10-07 20:03 UTC, shinehlina requested changes

2020-10-07 20:03 UTC, shinehlina commented on src/main/java/com/wine/to/up/simple/parser/service/ServiceApplication.java
> +import lombok.extern.slf4j.Slf4j;
Версию в помнике обновите

2020-10-07 20:03 UTC, shinehlina commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/Parser.java
> +    @SneakyThrows(IOException.class)
Мне кажется, что все-таки где-то надо его обработать

2020-10-07 20:03 UTC, shinehlina commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/SimpleWine.java
> +    public String toString() {
А почему вы убрали `@ToString`?

2020-10-07 20:03 UTC, shinehlina commented on src/main/resources/db/migration/V1.0.1__init.sql
> +    year INTEGER DEFAULT -1,
Создайте для этого новую миграцию

2020-10-09 13:46 UTC, DeLonghi commented on src/main/java/com/wine/to/up/simple/parser/service/ServiceApplication.java
> +import lombok.extern.slf4j.Slf4j;
Версию нашего сервиса или lombok?

2020-10-10 22:51 UTC, Anglopol requested changes

2020-10-10 22:51 UTC, Anglopol commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/Parser.java
> +    private String bottleYear = "";
У вас класс подразумевается как синглтон, но при этом у него есть состояние, что не очень хорошо, плюс когда видишь скласс парсер, совершенно неочевидно, что у него в какой-то момент времени может быть какое-то состояние
Сделайте его stateless, так будет правильнее

2020-10-10 22:51 UTC, Anglopol commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/Parser.java
> +            doc = Jsoup.connect(URL + "/catalog/vino/").get();
Перенесите значение строки в переменную, повысится читаемость, да и используется в нескольких местах она

2020-10-10 22:51 UTC, Anglopol commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/Parser.java
> +                doc = Jsoup.connect(URL + "/catalog/vino/page" + i).get();
Тоже можно в переменную

2020-10-10 22:51 UTC, Anglopol commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/Parser.java
> +                this.wineName = NameAndYear[0].replaceFirst("Вино ", "");
Странно использовать this где-либо, кроме конструктора

2020-10-10 22:51 UTC, Anglopol commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/Parser.java
> +                newWine = new SimpleWine(wineName, brandID, countryID, bottlePrice, bottleVolume, bottleABV, colorType,
Создавайте нове вино через билдер, конструктор с 8 параметрами выглядит страшно

2020-10-10 22:51 UTC, Anglopol commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/Parser.java
> +            countryEntity = countriesRepository.findCountryByCountryName(this.countryID);
Лучше поставьте тело else в фигурные скобки, так код будет выглядеть более единообразно

2020-10-10 22:51 UTC, Anglopol commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/SimpleWine.java
> +    @SneakyThrows(IOException.class)
Это зачем?

2020-10-10 22:51 UTC, Anglopol commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/Parser.java
> +    private void putInfoToDB() {
Странно, что у вас парсер и парсит и сохраняет что-то в бд, никакого сингл респосабилити. Лучше вынесете это поведение в отдельный сервис (постарайтесь сделать так, чтоб один сервис отвечал за что-то одно)

2020-10-10 22:51 UTC, Anglopol commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/Parser.java
>      private final String URL = "https://simplewine.ru";
Вынесите в проперти

2020-10-10 23:05 UTC, shinehlina requested changes

2020-10-10 23:05 UTC, shinehlina commented on src/main/java/com/wine/to/up/simple/parser/service/ServiceApplication.java
> +import lombok.extern.slf4j.Slf4j;
Да, сервиса, все правильно поняли)

2020-10-10 23:05 UTC, shinehlina commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/Parser.java
> +    private String bottleYear = "";
Плюсую, нехорошо

2020-10-10 23:05 UTC, shinehlina commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/Parser.java
> +            log.error("Catalog main page can`t be reached");
Звучит, как то, после чего парсинг должен остановиться. 
Вы же будете парсить то, что у вас в doc. Возможно, null, возможно - старую страницу. Не по-людски

2020-10-10 23:05 UTC, shinehlina commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/Parser.java
> +    private void putInfoToDB() {
Звучит валидно. Наверное, можете поправить это в pr за третий спринт.

2020-10-10 23:05 UTC, shinehlina commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/SimpleWine.java
> +    @SneakyThrows(IOException.class)
Не лайк за это

2020-10-11 18:38 UTC, DeLonghi commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/Parser.java
>      private final String URL = "https://simplewine.ru";
Единственный пункт с которым возникли проблемы во время фикса :( ПА-МА-ГИ-ТЕ

2020-10-11 22:07 UTC, shinehlina approved these changes

2020-10-11 22:08 UTC, shinehlina commented
Сори, случайно апрувнула)

2020-10-11 22:15 UTC, shinehlina commented on src/main/java/com/wine/to/up/simple/parser/service/configuration/ParaserConfig.java
> +public class ParaserConfig {
Это зачем?)

2020-10-11 22:15 UTC, shinehlina commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/Parser.java
>      private final String URL = "https://simplewine.ru";
А что за проблема?

2020-10-11 22:17 UTC, Anglopol commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/Parser.java
>      private final String URL = "https://simplewine.ru";
Если у вас возникают трудности - смело пишите в слак с описанием проблемы, будем разбираться

2020-10-11 22:21 UTC, shinehlina requested changes
Короче можете ване написать, что там с пропертями, спросить, критично ли. Плюс не очень понятный для меня конфиг

2020-10-11 22:22 UTC, shinehlina commented
А так надо в целом намного лучше)

2020-10-13 19:40 UTC, shinehlina approved these changes

2020-10-16 12:07 UTC, Anglopol approved these changes

2020-10-16 12:09 UTC, merged