Sprint 4
microservices-course-itmo/simple-parser-service pull request #35
Opened 2020-10-20 16:48 UTC by DeLonghi

2020-10-21 10:30 UTC, Anglopol requested changes

2020-10-21 10:30 UTC, Anglopol commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/CommonDbHandler.java
> +public class CommonDbHandler {
А как этот класс относится к db вообще?

2020-10-21 10:30 UTC, Anglopol commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/CommonDbHandler.java
> +    public UpdateProducts.Product putInfoToCommonDb(SimpleWine Wine) {
Вы же тут просто билдер вызываете по сути, вы ничего не кладете в базу, немного странное название

2020-10-21 10:30 UTC, Anglopol commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/DbHandler.java
> +    public void putInfoToDB(@NonNull SimpleWine newWine) {
Очень криво название выглядит, поменяйте на что-нибудь типа saveWine

2020-10-21 10:30 UTC, Anglopol commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/DbHandler.java
> +public class DbHandler {
Вообще данный класс лучше разбить на несколько отдельных, один пусть работает с вином, другой с виноградом, а третий с брендом и тд. Пусть основной класс у вас будет Wine сервис, который использует остальные сервисы

2020-10-21 10:30 UTC, Anglopol commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/Parser.java
> +    public static Document URLToDocument(String someURL) throws IOException {
Это точно должен делать парсер?

2020-10-21 10:30 UTC, Anglopol commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/Parser.java
> +        String region = "";
Я не особо понимаю, в чем смысл определения этих переменных до момента их использвания?

2020-10-21 10:30 UTC, Anglopol commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/ParserService.java
> +
Лишний пропуск

2020-10-21 10:30 UTC, Anglopol commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/ParserService.java
> +    private static String HOME_URL;
А чего они статик то вообще?

2020-10-21 10:30 UTC, Anglopol commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/ParserService.java
> +    public void setURLStatic(String URL_FROM_PROPERTY) {
Можно избавиться от этого метода и проставить все переменные с помощью value

2020-10-21 10:30 UTC, Anglopol commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/ParserService.java
> +
Пропуск

2020-10-21 10:30 UTC, Anglopol commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/ParserService.java
> +        for (int i = 0; i < 15; i++) {
Почему 15?

2020-10-21 10:30 UTC, Anglopol commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/ParserService.java
> +        for (int i = 0; i < 50; i++) {
Почему 50? Вынесите эти значение в какие-нибудь константы, иначе совершенно непонятно откуда они и что это такое вообще

2020-10-21 10:30 UTC, Anglopol commented on src/main/java/com/wine/to/up/simple/parser/service/configuration/KafkaConfiguration.java
> +//    BaseKafkaHandler<String> testTopicMessagesHandler(Properties consumerProperties,
Закоменченного кода быть не должно

2020-10-21 10:30 UTC, Anglopol commented on src/main/java/com/wine/to/up/simple/parser/service/controller/MainController.java
> +
Опять какие-то пропуски

2020-10-21 10:30 UTC, Anglopol commented on src/main/java/com/wine/to/up/simple/parser/service/messaging/SmopikTopicKafkaMessageHandler.java
> +//    public StringTopicKafkaMessageHandler(MessageRepository messageRepository) {
Уберите

2020-10-21 10:30 UTC, Anglopol commented on src/main/java/com/wine/to/up/simple/parser/service/messaging/TestTopicKafkaMessageHandler.java
> +//    public StringTopicKafkaMessageHandler(MessageRepository messageRepository) {
И это тоже

2020-10-21 10:30 UTC, Anglopol commented on src/test/java/com/wine/to/up/simple/parser/service/SimpleParser/ParserTest.java
> +
Пропуски уберите везде лишние

2020-10-21 11:12 UTC, shinehlina requested changes

2020-10-21 11:12 UTC, shinehlina commented on pom.xml
> +        <current-version>0.4.0</current-version>
Уберите тудухи, которые пофикшены

2020-10-21 11:12 UTC, shinehlina commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/CommonDbHandler.java
> +    public UpdateProducts.Product putInfoToCommonDb(SimpleWine Wine) {
Переменную со строчной)

2020-10-21 11:12 UTC, shinehlina commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/CommonDbHandler.java
> +                colorType = UpdateProducts.Product.Color.RED;
Лучше сделайте кейс на красное, а если не смогли - то надо об этом как-то сообщить в логах и пометить, что вино невалидное

2020-10-21 11:12 UTC, shinehlina commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/CommonDbHandler.java
> +                sugarType = UpdateProducts.Product.Sugar.DRY;
То же самое

2020-10-21 11:12 UTC, shinehlina commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/CommonDbHandler.java
> +                colorType = UpdateProducts.Product.Color.RED;
Или в самом апи есть unrecodnixed?

2020-10-22 21:52 UTC, 01gaM commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/ParserService.java
> +    public void setURLStatic(String URL_FROM_PROPERTY) {
С помощью @Value напрямую не удалось задать значения для static переменных
"Spring doesn't support @Value on static fields": https://www.baeldung.com/spring-inject-static-field

Для final переменных тоже пробовали задавать значения напрямую, не получилось. Нашли информацию о том, что final поля с помощью @Value могут быть заданы только через constructor injection.

2020-10-24 10:26 UTC, 01gaM commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/ParserService.java
> +    public void setURLStatic(String URL_FROM_PROPERTY) {
@Anglopol

2020-10-26 13:47 UTC, 01gaM commented on src/main/java/com/wine/to/up/simple/parser/service/controller/MainController.java
> +
Этот отступ необходим и создается сам при выполнении Code -> Reformat Code (Ctrl + Alt + L)

2020-10-26 16:01 UTC, DeLonghi commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/Parser.java
> +        String region = "";
Билдер жалуется, что переменная может быть неинициализированна

2020-10-28 17:25 UTC, shinehlina requested changes

2020-10-28 17:25 UTC, shinehlina commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/DbHandler/WineService.java
> +            log.error("DB error: problem with saveBrand");
Залогируйте саму ошибк

2020-10-28 17:25 UTC, shinehlina commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/DbHandler/WineService.java
> +            log.error("DB error: problem with saveCountry");
Здесб

2020-10-28 17:25 UTC, shinehlina commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/DbHandler/WineService.java
> +            log.error("DB error: problem with saveGrape");
Здесь

2020-10-28 17:25 UTC, shinehlina commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/DbHandler/WineService.java
> +        Wine wineEntity;
Лишняя строчка

2020-10-28 17:25 UTC, shinehlina commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/DbHandler/WineService.java
> +        wineEntity = new Wine();
Это тоже

2020-10-28 17:25 UTC, shinehlina commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/Parser.java
> +@NoArgsConstructor
Он нужен? Он и так создастся

2020-10-28 17:25 UTC, shinehlina commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/Parser.java
> +        return SimpleWine.builder().name(wineName).brandID(brandID).countryID(countryID).price(bottlePrice)
Лучше все-таки по строчкам. Вообще вы можете вообще не заводить переменных этих. Сразу работайте с билдером.

Ну типа такого
Builder wineBuilder = SimpleWine.builder();
builder = builder.name(wineDoc.getElementsByClass("product__header-russian-name").get(0).text());

2020-10-28 17:25 UTC, shinehlina commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/ParserService.java
> +        messageToKafka = message;
Это статическое поле для singleton, нехорошо. Может, его лучше вернуть?

2020-10-28 17:25 UTC, shinehlina commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/WineToDTO.java
> +                .setImage(wine.getPicture());
Посмотрите на model mapper. Настройте его на этом спринте, я запишу в цели, чтобы сейчас не блочиться

2020-10-28 17:25 UTC, shinehlina commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/WineToDTO.java
> +                log.error("The wine color was not defined.");
Добавьте, что за значение там непонятное

2020-10-28 17:25 UTC, shinehlina commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/WineToDTO.java
> +                sugarType = null;
И здесь

2020-10-28 17:25 UTC, shinehlina commented on src/main/resources/db/migration/V1.0.2__init.sql
> +
Вообще миграции менять нехорошо. ля этого нужно новую создать

2020-10-28 17:25 UTC, shinehlina commented on src/main/resources/db/migration/V1.0.2__init.sql
> +
Они для этого и есть

2020-10-29 18:39 UTC, Murwar commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/WineToDTO.java
> +                log.error("The wine color was not defined.");
Там пусто.  Для данных вин нет информации про цвет.  Также и с сахаром.  Я уже отписалась по этому поводу нашему BA,   вроде должны добавить unrecognized в parser-common-api.

2020-11-03 16:32 UTC, DeLonghi commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/Parser.java
> +        return SimpleWine.builder().name(wineName).brandID(brandID).countryID(countryID).price(bottlePrice)
В некст спринт сделаю!

2020-11-08 15:09 UTC, shinehlina commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/Parser.java
> +        return SimpleWine.builder().name(wineName).brandID(brandID).countryID(countryID).price(bottlePrice)
Я запомнила)

2020-11-08 15:12 UTC, DeLonghi commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/Parser.java
> +        return SimpleWine.builder().name(wineName).brandID(brandID).countryID(countryID).price(bottlePrice)
Хорошо :)

2020-11-08 15:13 UTC, shinehlina requested changes
У меня только остался вопрос к этому статическому полю. Что-то с ним ничего не происходит(

2020-11-08 15:13 UTC, shinehlina commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/ParserService.java
> +    private static UpdateProducts.UpdateProductsMessage messageToKafka;
Это до сих пор статическое поле и я до сих пор не понимаю его назначение

2020-11-09 07:02 UTC, Murwar commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/ParserService.java
> +    private static UpdateProducts.UpdateProductsMessage messageToKafka;
@shinehlina , это список вин, которые представлены как сообщение в Кафку. Данный список просто передается в контроллер для вывода всех этих вин на нашей 'home page' при переходе по соответсвующей ссылке.  Это было разработано на начальном этапе работы с Kafka для проверки правильности отправки сообщения. Так как всё сообщение не влезает в консоль, и некоторые поля закодированы, то данное показалось разумной и быстрой проверкой. 

При необходимости мы просто можем убрать данную функцию из контроллера.

2021-02-16 13:14 UTC, closed without merging