Sprint 5
microservices-course-itmo/simple-parser-service pull request #44
Opened 2020-10-27 17:13 UTC by DeLonghi

2020-11-04 16:33 UTC, shinehlina requested changes

2020-11-04 16:33 UTC, shinehlina commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/DbHandler/BrandsService.java
> +/** The service is responsible for adding a brand to DB.*/
Текст должен быть на отдельной строчке) 
```
  * <p>Проверяет, допустимый ли ход.</p>
  * <p>Например, чтобы задать ход e2-e4, напишите isValidMove(5,2,5,4);
  * Чтобы записать рокировку, укажите, откуда и куда ходит король.
  * Например, для короткой рокировки чёрных запишите isValidMove(5,8,7,8);</p>
  *
  * @param fromCol Вертикаль, на которой находится фигура (1=a, 8=h)
  * @param fromRow Горизонталь, на которой находится фигура (1...8)
  * @param toCol   Вертикаль клетки, на которую выполняется ход (1=a, 8=h)
  * @param toRow   Горизонталь клетки, на которую выполняется ход (1...8)
  * @return true, если ход допустим, и false, если недопустим
  */
```

2020-11-04 16:33 UTC, shinehlina commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/DbHandler/BrandsService.java
> +            log.trace("New Brand was added to DB: " + brand);
В логах используйте вот такое форматирование, это Sonar подсказывает обычно
`log.trace("New Brand was added to DB: {}",  brand);`

2020-11-04 16:33 UTC, shinehlina commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/DbHandler/BrandsService.java
> +/** The service is responsible for adding a brand to DB.*/
Это не только здесь

2020-11-04 16:33 UTC, shinehlina commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/DbHandler/BrandsService.java
> +            log.trace("New Brand was added to DB: " + brand);
Не только здесь

2020-11-04 16:33 UTC, shinehlina commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/DbHandler/BrandsService.java
> +     * @see BrandsRepository
Можно линки вставлять
`{@link BrandsRepository}`

2020-11-04 16:33 UTC, shinehlina commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/DbHandler/WineService.java
> +        Wine wineEntity = Wine.builder()
Model mapper здесь)

2020-11-04 16:33 UTC, shinehlina commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/Parser.java
> +        return SimpleWine.builder().name(wineName).brandID(brandID).countryID(countryID).price(bottlePrice)
Так, а следующий - это не этот? 
![image](https://user-images.githubusercontent.com/26968968/98137280-e04c6300-1ed2-11eb-8003-7847c13b92da.png)

2020-11-04 16:33 UTC, shinehlina commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/ParserService.java
> +            messageToKafka = UpdateProducts.UpdateProductsMessage.newBuilder().addAllProducts(products).build();
Это статическое поле для singleton, нехорошо. Может, его лучше вернуть?

2020-11-04 16:33 UTC, shinehlina commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/SimpleWine.java
> +    private Float discount;
На самом деле все-таки приятнее old/new price.

2020-11-04 16:33 UTC, shinehlina commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/WineToDTO.java
> +        UpdateProducts.Product.Builder product = UpdateProducts.Product.newBuilder()
model mapper?

2020-11-04 16:33 UTC, shinehlina commented on src/main/java/com/wine/to/up/simple/parser/service/configuration/KafkaConfiguration.java
> +        private String applicationConsumerGroupId;
Вы же не читаете из кафки

2020-11-04 16:33 UTC, shinehlina commented on src/main/java/com/wine/to/up/simple/parser/service/configuration/KafkaConfiguration.java
> +        Properties consumerProperties() {
Не читаете из кафки

2020-11-04 16:33 UTC, shinehlina commented on src/main/java/com/wine/to/up/simple/parser/service/configuration/KafkaConfiguration.java
> +        BaseKafkaHandler<UpdateProducts.UpdateProductsMessage> productTopicMessagesHandler(
Не читаете

2020-11-04 16:33 UTC, shinehlina commented on src/main/java/com/wine/to/up/simple/parser/service/configuration/KafkaConfiguration.java
> +        KafkaMessageSender<KafkaMessageSentEvent> testTopicKafkaMessageSender(Properties producerProperties,
Почему тут 2 сендера?

2020-11-04 16:33 UTC, shinehlina commented on src/main/java/com/wine/to/up/simple/parser/service/controller/MainController.java
> +    @Autowired
Идея должна сказать, что этоне рекомендуемый способ автовайринга

2020-11-04 16:33 UTC, shinehlina commented on src/main/java/com/wine/to/up/simple/parser/service/controller/MainController.java
> +        if (brandsRepository.existsBrandsByBrandName(wine.getBrandID().getBrandName())) {
Сликшом много логики для контроллера. По хорошему стоит это в сервис вынести (всю работу с репозиториями

2020-11-04 16:33 UTC, shinehlina commented on src/main/java/com/wine/to/up/simple/parser/service/messaging/serialization/EventDeserializer.java
> +    public UpdateProducts.UpdateProductsMessage deserialize(String topic, byte[] bytes) {
не читаете

2020-11-04 16:33 UTC, shinehlina commented
Закройте за предыдущие, чтобы не путаться)

2020-11-08 10:14 UTC, DeLonghi commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/Parser.java
> +        return SimpleWine.builder().name(wineName).brandID(brandID).countryID(countryID).price(bottlePrice)
Нет :)

2020-11-23 14:13 UTC, DeLonghi commented
Все измения в новых спринтах ✅

2020-11-23 16:02 UTC, shinehlina commented
Не очень удобно, что приходится смотреть в разные пр одновременно

2020-11-23 16:05 UTC, DeLonghi commented
Извиняемся. Так получилось :(

2021-02-16 13:15 UTC, closed without merging