Sprint 1
microservices-course-itmo/simple-parser-service pull request #7
Opened 2020-09-29 14:47 UTC by DeLonghi

2020-09-29 17:02 UTC, Anglopol requested changes

2020-09-29 17:02 UTC, Anglopol commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/ShopCatalog.java
> +    public int getWineID() {
Попробуйте почитать про lombok, это очень удобная штука, которая уже есть в проекте
https://projectlombok.org/
Это поможет вам сократить количество бойлерплейта

2020-09-29 17:02 UTC, Anglopol commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/Parser.java
> +        // logger = LoggerFactory.getLogger("ParserLogger");
Логгер можно заинжектить с помощью аннотации slf4j

2020-09-29 17:02 UTC, Anglopol commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/Parser.java
> +        float abv = 0;
Лучше использовать более информативные имена переменных
Плюс это не самый хороший пример создания переменных в самом верху функции. Их можно создавать по мере их надобности.

2020-09-29 17:02 UTC, Anglopol commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/ShopCatalog.java
> +        }finally{
Неправильное форматирование, используйте ctrl + alt + L перед созданием коммита.

2020-09-29 17:02 UTC, Anglopol commented on pom.xml
> +              <version>1.13.1</version>
Перенесите версию в проперти, пожалуйста

2020-09-29 17:02 UTC, Anglopol commented on pom.xml
> +            <version>4.12</version>
Это уже есть в spring test
Можно удалить :)

2020-09-29 17:32 UTC, Anglopol requested changes
Очень хорошо, комментарии скорее больше по оформлению и использованию некоторых фич

2020-09-29 17:32 UTC, Anglopol commented on .factorypath
> +    <factorypathentry kind="VARJAR" id="M2_REPO/com/wine/to/up/service-common-lib/0.2.1-SNAPSHOT/service-common-lib-0.2.1-SNAPSHOT.jar" enabled="true" runInBatchMode="false"/>
Это что такое?

2020-09-29 17:32 UTC, Anglopol commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/Parser.java
> +    private final int PAGES_TO_PARSE = 21; // < 132
Неинформативный комментарий

2020-09-29 17:32 UTC, Anglopol commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/Parser.java
> +    int n_pages;
Именование переменной нужно проводить в camelCase

2020-09-29 17:32 UTC, Anglopol commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/Parser.java
> +    public Parser() throws IOException {
Откуда Exception в конструкторе? Вы же вроде просто два списка создаете

2020-09-29 17:32 UTC, Anglopol commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/Parser.java
> +        int temp = doc.getElementsByAttributeValue("class", "pagination__navigation").size();
Лучше перенести весь хардкод в константы, назвать эти константы как-нибудь осмысленно

2020-09-29 17:32 UTC, Anglopol commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/ShopCatalog.java
> +                assert fr != null;
Откажитесь от ассертов, они проверяются только при запуске программы со специальным ключом. Не оень хорошая практика их использовать

2020-09-29 17:32 UTC, Anglopol commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/ShopCatalog.java
> +    public String toString() {
lombok генерит toString

2020-09-30 14:20 UTC, shinehlina requested changes

2020-09-30 14:20 UTC, shinehlina commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParserTest/WineShopTest.java
> +public class WineShopTest {
И еще мувните тесты. Они должны быть в папке src/test/java (не в мейне)

2020-09-30 14:20 UTC, shinehlina commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParserTest/WineShopTest.java
> +public class WineShopTest {
Проверьте, что при mvn clean install они запускаются и проходят

2020-09-30 14:20 UTC, shinehlina commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParserTest/WineShopTest.java
> +        wineShop = null;
Это зачем?)

2020-09-30 14:20 UTC, shinehlina commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParserTest/WineShopTest.java
> +    public TemporaryFolder temporaryFolder = new TemporaryFolder();
Вот это киньте выше, где поля объявляете

2020-09-30 14:20 UTC, shinehlina commented on src/main/java/com/wine/to/up/simple/parser/service/controller/MainController.java
> +    @PostMapping(path="/addGrape")
Path не должен содержать глаголов. "grape"

2020-09-30 14:20 UTC, shinehlina commented on src/main/java/com/wine/to/up/simple/parser/service/controller/MainController.java
> +    public @ResponseBody String addGrape(@RequestParam String grapeName){
Ставьте это над методом (как PostMapping)

2020-09-30 14:20 UTC, shinehlina commented on src/main/java/com/wine/to/up/simple/parser/service/domain/entity/Brands.java
> +    @Column(name = "brandname")
CamelCase

2020-09-30 14:20 UTC, shinehlina commented on src/main/java/com/wine/to/up/simple/parser/service/domain/entity/Brands.java
> +    public void writeInfoToFile(Brands someBrand) {
Не думаю, что это прямо в энтити надо делать

2020-10-04 17:36 UTC, shinehlina requested changes

2020-10-04 17:36 UTC, shinehlina commented on .factorypath
> +    <factorypathentry kind="VARJAR" id="M2_REPO/com/wine/to/up/service-common-lib/0.2.1-SNAPSHOT/service-common-lib-0.2.1-SNAPSHOT.jar" enabled="true" runInBatchMode="false"/>
Вы добавили же этот файл в gitignore. Тогда что он здесь делает?)

2020-10-04 17:36 UTC, shinehlina commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/Wine.java
> +        } catch (IOException e) {
Вы где-то этот файл вообще закрываете? Можете использовать try with resources

2020-10-04 17:36 UTC, shinehlina commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/Wine.java
> +        return "{name=" + this.name + ", brandID=" + this.brandID + ", countryID=" + this.countryID + ", price="
Если вы делаете JSON из класса, то используйте конвертеры

2020-10-04 17:36 UTC, shinehlina commented on src/main/resources/application.properties
> +spring.flyway.baseline-on-migrate=true
В идеале у вас не должно быть такого, чтобы падало с чексуммой. Для этого не нужно изменять существующие миграции. Как вы тогда будете проблему решать после деплоя?

2020-10-04 17:36 UTC, shinehlina commented on src/main/resources/application.properties
> +spring.flyway.baseline-on-migrate=true
Так что вам не нужна эта строчка

2020-10-04 17:38 UTC, shinehlina commented on src/main/java/com/wine/to/up/simple/parser/service/SimpleParser/Wine.java
> +        return "{name=" + this.name + ", brandID=" + this.brandID + ", countryID=" + this.countryID + ", price="
(Можете исправить это в следующем спринте)

2020-10-04 20:27 UTC, Murwar commented on src/main/resources/application.properties
> +spring.flyway.baseline-on-migrate=true
@shinehlina 
Это на время проектирования БД, так как часто менялась структура, я решила проблему именно так, потому что создавать каждый раз новую версию немного захламительно. У ребят тоже была проблема с flyway в какой-то момент, а clean, repair не помогали, так что написала и внесла данную строчку в общий код именно для этого. 

Далее же будут вноситься изменения с помощью новых версий миграции, а строчка будет закоменчена.

2020-10-05 11:09 UTC, shinehlina approved these changes

2020-10-05 11:22 UTC, Anglopol approved these changes
Немного отрефакторить еще бы, но перенесем это на следующий раз :)

2020-10-05 11:23 UTC, Anglopol commented
Можете мерджить

2020-10-05 11:23 UTC, merged